name: Pull code
run-name: ${{ github.actor }} is pulling code GitHub Actions
on:
  push:
    branches: [ main ]
jobs:
  pull_code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
